services:
  app_myhttp:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.myhttp
    environment:
      # HASURA_LOG_LEVEL: debug
      HASURA_SERVICE_TOKEN_SECRET: $APP_MYHTTP_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MYHTTP_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MYHTTP_OTEL_SERVICE_NAME
      ONESIGNAL_APP_ID: $APP_MYHTTP_ONESIGNAL_APP_ID
      ONESIGNAL_APP_ID_2: $APP_MYHTTP_ONESIGNAL_APP_ID_2
      ONESIGNAL_APP_KEY_TOKEN: $APP_MYHTTP_ONESIGNAL_APP_KEY_TOKEN
      ONESIGNAL_APP_KEY_TOKEN_2: $APP_MYHTTP_ONESIGNAL_APP_KEY_TOKEN_2
      ONESIGNAL_USER_KEY_TOKEN: $APP_MYHTTP_ONESIGNAL_USER_KEY_TOKEN
      ONESIGNAL_USER_KEY_TOKEN_2: $APP_MYHTTP_ONESIGNAL_USER_KEY_TOKEN_2
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8544:8080
